
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://samuelbuzas.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: "UA-120919437-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Samuel Buzas"
title: "{ Samuel Buzas }"
description: "Blog and portfolio site of Samuel Buzas, blogging mainly for tech. Opinions expressed are mine."
keywords: "buzas, samuel, personal, jekyll, theme"
favicon: "/assets/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/assets/img/black-lab-glass.ico"

background-img: "/assets/img/intro-bk.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello World!<br/>My Name is Samuel Buzas."
  - text: "Where’s your will to be weird?"
  - text: "That the powerful play goes on, and you may contribute a verse."

# me-img: "/assets/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/samwisebuze.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/assets/img/web-app/icon-36p.png"
icon-48p: "/assets/img/web-app/icon-48p.png"
icon-72p: "/assets/img/web-app/icon-72p.png"
icon-96p: "/assets/img/web-app/icon-96p.png"
icon-144p: "/assets/img/web-app/icon-144p.png"
icon-192p: "/assets/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "samuelbuzas"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/assets/img/timeline/spidertocat.png"
    date: "Current"
    description: "Software Analyst Coop at Learn21"
  - image: "/assets/img/timeline/glimmar-icon.png"
    date: "Current"
    description: "Back-End Developer for Glimmar"
  - image: "/assets/img/timeline/baracktocat.jpg"
    date: "August 2017 - December 2017"
    description: "Software Engineer Coop with ICR"
  - image: "/assets/img/timeline/spidertocat.png"
    date: "August 2015"
    description: "Started college at UC!"


  

# First image of the Timeline

timeline-img: "/assets/img/timeline/default.png"

###########
# Contact #
###########

email: "buzassg@mail.uc.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Samuel Buzas is an awesome person. He lives in Cincinnati, where he studies Computer Science and works as a Full-stack wdWeb Developer. In his spare time, Sam likes to play Dungeons and Dragons."
author_blurb_image: "/assets/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/samwisebuze"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/assets/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: sbuzas
keybase-in-social: True
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

# HTML minification
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
  envs: []
  blanklines: true
  profile: false
  startings: []

gems:
  - jekyll-paginate
  - jemoji
